# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 661)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BtnListele = QtWidgets.QPushButton(self.centralwidget)
        self.BtnListele.setGeometry(QtCore.QRect(530, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BtnListele.setFont(font)
        self.BtnListele.setObjectName("BtnListele")
        self.CmbDers = QtWidgets.QComboBox(self.centralwidget)
        self.CmbDers.setGeometry(QtCore.QRect(460, 70, 131, 21))
        self.CmbDers.setObjectName("CmbDers")
        self.CmbDers.addItem("")
        self.CmbDers.addItem("")
        self.CmbDers.addItem("")
        self.CmbDers.addItem("")
        self.CmbDers.addItem("")
        self.CmbDers.addItem("")
        self.CmbDers.addItem("")
        self.CmbDers.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 78, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.BtnGuncelle = QtWidgets.QPushButton(self.centralwidget)
        self.BtnGuncelle.setGeometry(QtCore.QRect(370, 310, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BtnGuncelle.setFont(font)
        self.BtnGuncelle.setObjectName("BtnGuncelle")
        self.LnaAdres = QtWidgets.QLineEdit(self.centralwidget)
        self.LnaAdres.setGeometry(QtCore.QRect(460, 200, 241, 71))
        self.LnaAdres.setObjectName("LnaAdres")
        self.BtnCikis = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCikis.setGeometry(QtCore.QRect(710, 310, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BtnCikis.setFont(font)
        self.BtnCikis.setObjectName("BtnCikis")
        self.LnaOkulno = QtWidgets.QLineEdit(self.centralwidget)
        self.LnaOkulno.setGeometry(QtCore.QRect(150, 70, 133, 20))
        self.LnaOkulno.setObjectName("LnaOkulno")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 71, 44, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.LnaSoyadi = QtWidgets.QLineEdit(self.centralwidget)
        self.LnaSoyadi.setGeometry(QtCore.QRect(150, 190, 133, 20))
        self.LnaSoyadi.setObjectName("LnaSoyadi")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 85, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.TblWiBilgiler = QtWidgets.QTableWidget(self.centralwidget)
        self.TblWiBilgiler.setGeometry(QtCore.QRect(30, 380, 771, 221))
        self.TblWiBilgiler.setRowCount(50)
        self.TblWiBilgiler.setColumnCount(9)
        self.TblWiBilgiler.setObjectName("TblWiBilgiler")
        self.LnaAdi = QtWidgets.QLineEdit(self.centralwidget)
        self.LnaAdi.setGeometry(QtCore.QRect(150, 130, 133, 20))
        self.LnaAdi.setObjectName("LnaAdi")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 31, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ChkBoxDevam = QtWidgets.QCheckBox(self.centralwidget)
        self.ChkBoxDevam.setGeometry(QtCore.QRect(460, 140, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ChkBoxDevam.setFont(font)
        self.ChkBoxDevam.setObjectName("ChkBoxDevam")
        self.LnaTelefonu = QtWidgets.QLineEdit(self.centralwidget)
        self.LnaTelefonu.setGeometry(QtCore.QRect(150, 260, 133, 20))
        self.LnaTelefonu.setObjectName("LnaTelefonu")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 64, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 200, 56, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 140, 59, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.BtnAra = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAra.setGeometry(QtCore.QRect(260, 310, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BtnAra.setFont(font)
        self.BtnAra.setObjectName("BtnAra")
        self.BtnKaydet = QtWidgets.QPushButton(self.centralwidget)
        self.BtnKaydet.setGeometry(QtCore.QRect(30, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BtnKaydet.setFont(font)
        self.BtnKaydet.setObjectName("BtnKaydet")
        self.BtnSil = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSil.setGeometry(QtCore.QRect(150, 310, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BtnSil.setFont(font)
        self.BtnSil.setObjectName("BtnSil")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 10, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnListele.setText(_translate("MainWindow", "KAYITLARI LİSTELE"))
        self.CmbDers.setItemText(0, _translate("MainWindow", "MATEMATİK"))
        self.CmbDers.setItemText(1, _translate("MainWindow", "FİZİK"))
        self.CmbDers.setItemText(2, _translate("MainWindow", "KİMYA"))
        self.CmbDers.setItemText(3, _translate("MainWindow", "EDEBİYAT"))
        self.CmbDers.setItemText(4, _translate("MainWindow", "FELSEFE"))
        self.CmbDers.setItemText(5, _translate("MainWindow", "RESİM"))
        self.CmbDers.setItemText(6, _translate("MainWindow", "TARİH"))
        self.CmbDers.setItemText(7, _translate("MainWindow", "COĞRAFYA"))
        self.label.setText(_translate("MainWindow", "OKUL NO "))
        self.BtnGuncelle.setText(_translate("MainWindow", "KAYIT GÜNCELLE"))
        self.BtnCikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.label_5.setText(_translate("MainWindow", "DERS"))
        self.label_4.setText(_translate("MainWindow", "TELEFONU"))
        self.label_2.setText(_translate("MainWindow", "ADI"))
        self.ChkBoxDevam.setText(_translate("MainWindow", "DEVAM EDİLDİ"))
        self.label_3.setText(_translate("MainWindow", "SOYADI"))
        self.label_6.setText(_translate("MainWindow", "ADRES"))
        self.label_7.setText(_translate("MainWindow", "DEVAM"))
        self.BtnAra.setText(_translate("MainWindow", "KAYIT ARA"))
        self.BtnKaydet.setText(_translate("MainWindow", "KAYIT EKLE"))
        self.BtnSil.setText(_translate("MainWindow", "KAYIT SİL"))
        self.label_8.setText(_translate("MainWindow", "DERS TAKİP PROJESİ/  Abdullah Mesut Yıldırım  / 05369515189"))
